MetEX-Rails/config/routes.rb
Rails.application.routes.draw do
	root 'welcome#index'
	
	get 'tour/:line_slug/:station_slug', to: 'stations#show', as: :station
	
	resources :lines, param: :slug, only: :index do
		resources :stations, only: :index
	end
	
	resources :places, param: :slug, only: [:index, :show]
	
	namespace :admin do
		resources :lines, except: :index do
			resources :stations, except: [:index, :show]
		end
		
		resources :places, except: :show
		resources :movements, :interchanges, :images, :sounds
	end
end

MetEX-Rails/app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :imageable, polymorphic: true
	
	validates :filename, :title, :alt, :imageable, presence: true
	validates :filename, format: { with: /[\w\/-]+\.jpg\z/, message: "must end in .jpg" }
	
	def url
		"#{Rails.application.config.asset_server}/#{Rails.application.config.asset_image_path}/stations/#{filename}"
	end
end

MetEX-Rails/app/models/interchange.rb
class Interchange < ActiveRecord::Base
	has_many :stations, -> { includes(:line).order('lines.order') }
	
	validates :name, presence: true, uniqueness: true
	
	extend FriendlyId
	friendly_id :name, use: :slugged
end

MetEX-Rails/app/models/line.rb
class Line < ActiveRecord::Base
	has_many :stations
	
	validates :name, presence: true, uniqueness: true, length: { maximum: 5 }
	
	default_scope { where(active: true).order(:order) }
	
	extend FriendlyId
	friendly_id :name, use: :slugged
	
	def name_components
		{ number: name[/^(\d+)/, 1], suffix: name[/\d+([a-z]+)$/, 1] }
	end
end

MetEX-Rails/app/models/movement.rb
class Movement < ActiveRecord::Base
	belongs_to :up_station, class_name: 'Station', inverse_of: :down_movements
	belongs_to :down_station, class_name: 'Station', inverse_of: :up_movements
	has_and_belongs_to_many :stations
	
	validates :stations, presence: true
	validate :both_stations_cannot_be_nil
	
	private
		def both_stations_cannot_be_nil
			if up_station_id.blank? && down_station_id.blank?
				errors.add(:base, "both stations can't be empty")
			end
		end
end

MetEX-Rails/app/models/place.rb
class Place < ActiveRecord::Base
	has_many :images, as: :imageable
	has_and_belongs_to_many :stations, -> { includes(:line).order('lines.order') }
	
	validates :name, :description, :stations, presence: true
	validates :name, uniqueness: true
	
	default_scope { order(name: :asc) }
	
	extend FriendlyId
	friendly_id :name, use: :slugged
end

MetEX-Rails/app/models/sound.rb
class Sound < ActiveRecord::Base
	belongs_to :soundable, polymorphic: true
	
	validates :filename, :title, :length, :soundable, presence: true
	validates :filename, uniqueness: true, format: { with: /[\w\/]+\.mp3\z/, message: "must end in .mp3" }
	validates :length, numericality: { only_integer: true }
	
	def url
		"#{Rails.application.config.asset_server}/#{Rails.application.config.asset_sound_path}/#{filename}"
	end
end

MetEX-Rails/app/models/station.rb
class Station < ActiveRecord::Base
	belongs_to :line
	belongs_to :interchange
	has_one :sound, as: :soundable
	has_many :images, as: :imageable
	has_many :up_movements, -> { order(up_allowed: :desc) }, class_name: 'Movement', foreign_key: 'down_station_id', inverse_of: :down_station
	has_many :down_movements, -> { order(down_allowed: :desc) }, class_name: 'Movement', foreign_key: 'up_station_id', inverse_of: :up_station
	has_and_belongs_to_many :movements
	has_and_belongs_to_many :places
	
	validates :name, :line, presence: true
	validates :name, uniqueness: { scope: :line }
	
	default_scope { where(active: true) }
	
	extend FriendlyId
	friendly_id :name, use: :scoped, scope: :line
end

MetEX-Rails/app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :restrict_to_development
	
	protected
		def restrict_to_development
			head(:not_found) unless Rails.env.development?
		end	
end

MetEX-Rails/app/controllers/lines_controller.rb
class LinesController < ApplicationController
	# GET /lines
	def index
		@lines = Line.all
	end
end

MetEX-Rails/app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :set_place, only: :show

	# GET /places
	def index
		@places = Place.all
	end

	# GET /places/1
	def show
	end

	private
		def set_place
			@place = Place.friendly.find(params[:slug])
		end
end

MetEX-Rails/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

MetEX-Rails/app/helpers/application_helper.rb
module ApplicationHelper
end

MetEX-Rails/app/helpers/images_helper.rb
module ImagesHelper
end

MetEX-Rails/app/helpers/interchanges_helper.rb
module InterchangesHelper
end

MetEX-Rails/app/helpers/lines_helper.rb
module LinesHelper
end

MetEX-Rails/app/helpers/movements_helper.rb
module MovementsHelper
end

MetEX-Rails/app/helpers/places_helper.rb
module PlacesHelper
end

MetEX-Rails/app/helpers/sounds_helper.rb
module SoundsHelper
end

MetEX-Rails/app/helpers/stations_helper.rb
module StationsHelper
	def link_to_next_station(station, allowed = false)
		if station
			not_allowed_class = 'bg-danger' unless allowed
			link_to station.name, station_path(station.line.slug, station.slug), class: not_allowed_class
		else
			"Terminus"
		end
	end
end

MetEX-Rails/app/helpers/welcome_helper.rb
module WelcomeHelper
end

MetEX-Rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MétEX, the Paris Métro experience: <%= yield(:title) %></title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<%= link_to raw('mét<strong>ex</strong>'), root_path, class: 'navbar-brand' %>
			</div>
			<div class="collapse navbar-collapse" id="navbar-collapse">
				<ul class="nav navbar-nav">
					<li><%= link_to 'lines', lines_path %></li>
					<li><%= link_to 'places', places_path %></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to 'report issue on GitHub', 'https://github.com/PkerUNO/MetEX/issues', data: { confirm: 'Please report only bugs and suggestions to do with the workings of the site and not the content. I am aware the line data and photos are out of date, these will be updated in a future version.' } %></li>
				</ul>
			</div>
		</div>
	</nav>
<%= yield %>
	<div class="container-fluid">
		<div class="row">
			<div class="col-xs-12">
				<p class="well well-sm text-center"><small>&copy;2005-2015 Richard Whittaker - Milestone <em><%= Rails.application.config.milestone_name %></em> - <%= link_to 'Please report any bugs on GitHub', 'https://github.com/PkerUNO/MetEX/issues', data: { confirm: 'Please report only bugs and suggestions to do with the workings of the site and not the content. I am aware the line data and photos are out of date, these will be updated in a future version.' } %></small></p>
			</div>
		</div>
	</div>
</body>
</html>