MetEX-Rails/config/routes.rb
Rails.application.routes.draw do
	root 'welcome#index'
	
	get 'tour/:line_slug/:station_slug', to: 'stations#show', as: :station
	
	resources :lines, param: :slug, only: :index do
		resources :stations, only: :index
	end
	
	resources :places, param: :slug, only: [:index, :show]
	
	namespace :admin do
		resources :lines, except: :index do
			resources :stations, except: [:index, :show]
		end
		
		resources :places, except: :show
		resources :movements, :interchanges, :images, :sounds
	end
end

MetEX-Rails/app/models/image.rb
class Image < ActiveRecord::Base
	belongs_to :imageable, polymorphic: true
	
	validates :filename, :title, :alt, :imageable, presence: true
	validates :filename, format: { with: /[\w\/-]+\.jpg\z/, message: "must end in .jpg" }
	
	def url
		"#{Rails.application.config.asset_server}/#{Rails.application.config.asset_image_path}/stations/#{filename}"
	end
end

MetEX-Rails/app/models/interchange.rb
class Interchange < ActiveRecord::Base
	has_many :stations, -> { includes(:line).order('lines.order') }
	
	validates :name, presence: true, uniqueness: true
	
	extend FriendlyId
	friendly_id :name, use: :slugged
end

MetEX-Rails/app/models/line.rb
class Line < ActiveRecord::Base
	has_many :stations
	
	validates :name, presence: true, uniqueness: true, length: { maximum: 5 }
	
	default_scope { where(active: true).order(:order) }
	
	extend FriendlyId
	friendly_id :name, use: :slugged
	
	def name_components
		{ number: name[/^(\d+)/, 1], suffix: name[/\d+([a-z]+)$/, 1] }
	end
end

MetEX-Rails/app/models/movement.rb
class Movement < ActiveRecord::Base
	belongs_to :up_station, class_name: 'Station', inverse_of: :down_movements
	belongs_to :down_station, class_name: 'Station', inverse_of: :up_movements
	has_and_belongs_to_many :stations
	
	validates :stations, presence: true
	validate :both_stations_cannot_be_nil
	
	private
		def both_stations_cannot_be_nil
			if up_station_id.blank? && down_station_id.blank?
				errors.add(:base, "both stations can't be empty")
			end
		end
end

MetEX-Rails/app/models/place.rb
class Place < ActiveRecord::Base
	has_many :images, as: :imageable
	has_and_belongs_to_many :stations, -> { includes(:line).order('lines.order') }
	
	validates :name, :description, :stations, presence: true
	validates :name, uniqueness: true
	
	default_scope { order(name: :asc) }
	
	extend FriendlyId
	friendly_id :name, use: :slugged
end

MetEX-Rails/app/models/sound.rb
class Sound < ActiveRecord::Base
	belongs_to :soundable, polymorphic: true
	
	validates :filename, :title, :length, :soundable, presence: true
	validates :filename, uniqueness: true, format: { with: /[\w\/]+\.mp3\z/, message: "must end in .mp3" }
	validates :length, numericality: { only_integer: true }
	
	def url
		"#{Rails.application.config.asset_server}/#{Rails.application.config.asset_sound_path}/#{filename}"
	end
end

MetEX-Rails/app/models/station.rb
class Station < ActiveRecord::Base
	belongs_to :line
	belongs_to :interchange
	has_one :sound, as: :soundable
	has_many :images, as: :imageable
	has_many :up_movements, -> { order(up_allowed: :desc) }, class_name: 'Movement', foreign_key: 'down_station_id', inverse_of: :down_station
	has_many :down_movements, -> { order(down_allowed: :desc) }, class_name: 'Movement', foreign_key: 'up_station_id', inverse_of: :up_station
	has_and_belongs_to_many :movements
	has_and_belongs_to_many :places
	
	validates :name, :line, presence: true
	validates :name, uniqueness: { scope: :line }
	
	default_scope { where(active: true) }
	
	extend FriendlyId
	friendly_id :name, use: :scoped, scope: :line
end

MetEX-Rails/app/controllers/admin/sounds_controller.rb
class Admin::SoundsController < AdminController
	before_action :set_sound, only: [:show, :edit, :update, :destroy]

	# GET /sounds
	def index
		@sounds = Sound.all
	end

	# GET /sounds/1
	def show
	end

	# GET /sounds/new
	def new
		@sound = Sound.new
	end

	# GET /sounds/1/edit
	def edit
	end

	# POST /sounds
	def create
		@sound = Sound.new(sound_params)

		if @sound.save
			redirect_to @sound, notice: 'Sound was successfully created.'
		else
			render :new
		end
	end

	# PATCH/PUT /sounds/1
	def update
		if @sound.update(sound_params)
			redirect_to @sound, notice: 'Sound was successfully updated.'
		else
			render :edit
		end
	end

	# DELETE /sounds/1
	def destroy
		@sound.destroy
		redirect_to sounds_url, notice: 'Sound was successfully destroyed.'
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_sound
			@sound = Sound.find(params[:id])
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def sound_params
			params.require(:sound).permit(:filename, :title, :length, :soundable)
		end
end

MetEX-Rails/app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :restrict_to_development
	
	protected
		def restrict_to_development
			head(:not_found) unless Rails.env.development?
		end	
end

MetEX-Rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
end

MetEX-Rails/app/controllers/lines_controller.rb
class LinesController < ApplicationController
	# GET /lines
	def index
		@lines = Line.all
	end
end

MetEX-Rails/app/controllers/places_controller.rb
class PlacesController < ApplicationController
	before_action :set_place, only: :show

	# GET /places
	def index
		@places = Place.all
	end

	# GET /places/1
	def show
	end

	private
		def set_place
			@place = Place.friendly.find(params[:slug])
		end
end

MetEX-Rails/app/controllers/stations_controller.rb
class StationsController < ApplicationController
	before_action :set_line
	before_action :set_station, only: :show
	before_action :set_movements, only: :show

	# GET /stations
	def index
		@stations = @line.stations
	end

	# GET /stations/1
	def show
		 set_connections if @station.interchange
	end

	private
		# Get Line first due to nested routing
		def set_line
			@line = Line.friendly.find(params[:line_slug])
		end

		def set_station
			@station = @line.stations.friendly.find(params[:station_slug])
		end
		
		def set_movements
			@up_movements = @station.up_movements
			@down_movements = @station.down_movements
		end
		
		def set_connections
			@connections = Interchange.find(@station.interchange.id).stations.where.not(id: @station)
		end
end

MetEX-Rails/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

MetEX-Rails/app/helpers/admin/sounds_helper.rb
module Admin::SoundsHelper
end

MetEX-Rails/app/helpers/application_helper.rb
module ApplicationHelper
end

MetEX-Rails/app/helpers/images_helper.rb
module ImagesHelper
end

MetEX-Rails/app/helpers/interchanges_helper.rb
module InterchangesHelper
end

MetEX-Rails/app/helpers/lines_helper.rb
module LinesHelper
end

MetEX-Rails/app/helpers/movements_helper.rb
module MovementsHelper
end

MetEX-Rails/app/helpers/places_helper.rb
module PlacesHelper
end

MetEX-Rails/app/helpers/sounds_helper.rb
module SoundsHelper
end

MetEX-Rails/app/helpers/stations_helper.rb
module StationsHelper
	def link_to_next_station(station, allowed = false)
		if station
			not_allowed_class = 'bg-danger' unless allowed
			link_to station.name, station_path(station.line.slug, station.slug), class: not_allowed_class
		else
			"Terminus"
		end
	end
end

MetEX-Rails/app/helpers/welcome_helper.rb
module WelcomeHelper
end

MetEX-Rails/app/views/admin/sounds/_form.html.erb
<%= form_for [:admin, @sound] do |f| %>
  <% if @sound.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sound.errors.count, "error") %> prohibited this sound from being saved:</h2>

      <ul>
      <% @sound.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :filename %><br>
    <%= f.text_field :filename %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :length %><br>
    <%= f.number_field :length %>
  </div>
  <div class="field">
    <%= f.label :soundable %><br>
    <%= f.text_field :soundable %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MetEX-Rails/app/views/admin/sounds/edit.html.erb
<h1>Editing Sound</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @sound] %> |
<%= link_to 'Back', admin_sounds_path %>

MetEX-Rails/app/views/admin/sounds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sounds</h1>

<table>
  <thead>
    <tr>
      <th>Filename</th>
      <th>Title</th>
      <th>Length</th>
      <th>Soundable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sounds.each do |sound| %>
      <tr>
        <td><%= sound.filename %></td>
        <td><%= sound.title %></td>
        <td><%= sound.length %></td>
        <td><%= sound.soundable %></td>
        <td><%= link_to 'Show', [:admin, sound] %></td>
        <td><%= link_to 'Edit', edit_admin_sound_path(sound) %></td>
        <td><%= link_to 'Destroy', [:admin, sound], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sound', new_admin_sound_path %>

MetEX-Rails/app/views/admin/sounds/new.html.erb
<h1>New Sound</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_sounds_path %>

MetEX-Rails/app/views/admin/sounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Filename:</strong>
  <%= @sound.filename %>
</p>

<p>
  <strong>Title:</strong>
  <%= @sound.title %>
</p>

<p>
  <strong>Length:</strong>
  <%= @sound.length %>
</p>

<p>
  <strong>Soundable:</strong>
  <%= @sound.soundable %>
</p>

<%= link_to 'Edit', edit_admin_sound_path(@sound) %> |
<%= link_to 'Back', admin_sounds_path %>